export const menuItems = [
  {
    id: 1,
    name: "Boerewors Roll",
    category: "Meal",
    price: 35,
    description: "A juicy grilled boerewors sausage on a fresh roll, served with optional sauce.",
    image: "/images/boerewors-roll.png",
  },
 

  {
    id: 2,
    name: "4 Wings and Chips",
    category: "Meal",
    price: 80,
    description: "Four crispy fried wings served with golden fries.",
    image: "/images/wings.png",
  },
  {
    id: 3,
    name: "5 Wings and Chips",
    category: "Meal",
    price: 105,
    description: "Five spicy wings served with fries — perfect for wing lovers.",
    image: "/images/wings.png",
  },
  {
    id: 4,
    name: "Russian Kota",
    category: "Kota",
    price: 30,
    description: "Classic kota stuffed with a Russian sausage and fresh toppings.",
    image: "/images/kota.png",
  },
  {
    id: 5,
    name: "Cheese & Polony Kota",
    category: "Kota",
    price: 25,
    description: "A local favorite: melty cheese, polony and sauces in a toasted quarter loaf.",
    image: "/images/kota.png",
  },
  {
    id: 6,
    name: "Sum Local Kota",
    category: "Kota",
    price: 55,
    description: "Our signature Kota packed with meats, sauces, and township flavor.",
    image: "/images/sum -kota.png",
  },
  {
    id: 7,
    name: "Kota",
    category: "Kota",
    price: 40,
    description: "A traditional South African street food in a quarter loaf.",
    image: "/images/kota.png",
  },
  {
    id: 8,
    name: "Small Chips",
    category: "Chips",
    price: 25,
    description: "Crispy golden fries — perfect for a light snack.",
    image: "/images/small-chips.png",
  },
  {
    id: 9,
    name: "Large Chips",
    category: "Chips",
    price: 40,
    description: "A large portion of crispy fries for big appetites.",
    image: "/images/small-chips.png",
  },
  {
    id: 10,
    name: "Coca-Cola 440ml",
    category: "Drinks",
    price: 17,
    description: "Classic Coca-Cola in a 440ml can.",
    image: "/images/coca-cola.png",
  },
  {
    id: 11,
    name: "Play",
    category: "Drinks",
    price: 22,
    description: "Fruity and energizing sports drink.",
    image: "/images/play.jpg",
  },
  {
    id: 12,
    name: "Monster",
    category: "Drinks",
    price: 23,
    description: "Bold energy drink with a strong caffeine boost.",
    image: "/images/monster.png",
  },
  {
    id: 13,
    name: "Water",
    category: "Drinks",
    price: 10,
    description: "500ml bottled water — stay hydrated.",
    image: "/images/water.png",
  },
  {
    id: 14,
    name: "Liqui-Fruit Juice",
    category: "Drinks",
    price: 20,
    description: "100% real fruit juice in a variety of flavors.",
    image: "/images/liquifruit.png",
  },
  {
    id: 15,
    name: "Powerade",
    category: "Drinks",
    price: 18,
    description: "Isotonic sports drink for energy and hydration.",
    image: "/images/powerade.png",
  },
  {
    id: 16,
    name: "Cappy",
    category: "Drinks",
    price: 20,
    description: "Refreshing fruit drink — smooth and light.",
    image: "/images/cappy.png",
  },
  {
    id: 17,
    name: "Reboost",
    category: "Drinks",
    price: 16,
    description: "Affordable energy drink with a kick.",
    image: "/images/reboost.png",
  },
  {
    id: 18,
    name: "Score",
    category: "Drinks",
    price: 17,
    description: "Popular energy drink with bold taste.",
    image: "/images/score.png",
  },
  {
    id: 19,
    name: "Sum Local Burger",
    category: "Burger",
    price: 35,
    description: "House-styleburger with your choice of sauce.",
    image: "/images/sum-local-burger.png",
  },
];
